### ISSUE TITLE
lora模型大小是否可调？

### ISSUE THREAD

**Issue by ZhibinPeng** [7eu7d7/HCP-Diffusion#25]

**Comment by ZhibinPeng** [comment]
可以想lora-script一样能够通过network_dim调整模型大小吗？

**Comment by 7eu7d7** [comment]
可以调整rank，可以每层的lora都给不同的rank。比如```lora_conventional.yaml```里面定义的unet部分的lora。
```yaml
lora_unet:
  -
    lr: 1e-4
    rank: 8
    layers:
      - 're:.*\.attn.?$'
      - 're:.*\.ff$'
```
rank可以是小数，表示按所在层输出维度的比例去设定rank。比如rank=0.025，对输出维度320的层，实际rank是8，对输出维度1280的层，rank是32。按比例给rank更合理一些。

**Comment by 7eu7d7** [comment]
比如这种写法，就给```注意力层```和```ff层```有不同的学习率和rank值(network_dim)
```yaml
lora_unet:
  -
    lr: 1e-4
    rank: 8
    layers:
      - 're:.*\.attn.?$'
  -
    lr: 2e-4
    rank: 0.05
    layers:
      - 're:.*\.attn.?$'
```

**Comment by ZhibinPeng** [comment]
```
lora_unet:
  -
    lr: 1e-4
    rank: 32
    layers:
      - 're:.*\.attn.?$'
      - 're:.*\.ff$'
```
直接写成这样是否可行？

**Comment by ZhibinPeng** [comment]
比如rank=0.025，对输出维度320的层，实际rank是8，对输出维度1280的层，rank是32。按比例给rank更合理一些。
这里还不是很理解，可能再讲讲嘛，感谢感谢

**Comment by 7eu7d7** [comment]
> 比如rank=0.025，对输出维度320的层，实际rank是8，对输出维度1280的层，rank是32。按比例给rank更合理一些。 这里还不是很理解，可能再讲讲嘛，感谢感谢

unet部分，各个层的输出维度(dim)是不一样的，rank设置成小数就会根据输出维度，自动为各个层上的lora按比例分配不同的rank。

**Comment by ZhibinPeng** [comment]
```
lr: 1e-4
    rank: 8
    layers:
      - 're:.*\.attn.?$'
  -
    lr: 2e-4
    rank: 0.05
    layers:
      - 're:.*\.ff$'
```
为什么ff层对应的就是0.05的rank值，而attention对应的是0.025×320=8的rank值
