### ISSUE TITLE
现在这个仓库训练的lora可以用在webui等地方么

### ISSUE THREAD

**Issue by iamwangyabin** [7eu7d7/HCP-Diffusion#5]

**Comment by iamwangyabin** [comment]
好吧，我刚试下第一步没走通：
`
(hcp) yabin@EC028B:~/HCP-Diffusion$ hcpinit .
Traceback (most recent call last):
  File "/home/yabin/HCP-Diffusion/hcpdiff/tools/init_proj.py", line 11, in main
    shutil.copytree(os.path.join(sys.prefix, 'hcpdiff/cfgs'), r'./cfgs')
  File "/home/yabin/miniconda3/envs/hcp/lib/python3.10/shutil.py", line 557, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yabin/miniconda3/envs/hcp/hcpdiff/cfgs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yabin/miniconda3/envs/hcp/bin/hcpinit", line 33, in <module>
    sys.exit(load_entry_point('hcpdiff', 'console_scripts', 'hcpinit')())
  File "/home/yabin/HCP-Diffusion/hcpdiff/tools/init_proj.py", line 14, in main
    shutil.copytree(os.path.join(sys.prefix, '../hcpdiff/cfgs'), r'./cfgs')
  File "/home/yabin/miniconda3/envs/hcp/lib/python3.10/shutil.py", line 557, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yabin/miniconda3/envs/hcp/../hcpdiff/cfgs'
(hcp) yabin@teddy-SYS-4029GP-TRTC-EC028B:~/HCP-Diffusion$ hcpinit
Traceback (most recent call last):
  File "/home/yabin/HCP-Diffusion/hcpdiff/tools/init_proj.py", line 11, in main
    shutil.copytree(os.path.join(sys.prefix, 'hcpdiff/cfgs'), r'./cfgs')
  File "/home/yabin/miniconda3/envs/hcp/lib/python3.10/shutil.py", line 557, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yabin/miniconda3/envs/hcp/hcpdiff/cfgs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yabin/miniconda3/envs/hcp/bin/hcpinit", line 33, in <module>
    sys.exit(load_entry_point('hcpdiff', 'console_scripts', 'hcpinit')())
  File "/home/yabin/HCP-Diffusion/hcpdiff/tools/init_proj.py", line 14, in main
    shutil.copytree(os.path.join(sys.prefix, '../hcpdiff/cfgs'), r'./cfgs')
  File "/home/yabin/miniconda3/envs/hcp/lib/python3.10/shutil.py", line 557, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yabin/miniconda3/envs/hcp/../hcpdiff/cfgs'

`

**Comment by 7eu7d7** [comment]
直接git clone的可以不需要hcpinit，这个是通过pip install之后，你新建工程使用时候运行的。近期会考虑增加对webui的转换脚本。

**Comment by iamwangyabin** [comment]
好的，我已经成功训练一个lora了，但是有个问题，我发现我没法加载nai，只能用sd-1.5，不知道这是配置有啥问题么？
```

_base_: [cfgs/train/train_base.yaml, cfgs/train/tuning_base.yaml]

lora_unet:
  - lr: 1e-4
    rank: 8
    layers:
      - 're:.*\.attn.?$'
      - 're:.*\.ff\.net\.0$'

lora_text_encoder:
  - lr: 1e-5
    rank: 4
    layers:
      - 're:.*self_attn$'
      - 're:.*mlp$'

tokenizer_pt:
  train: null

train:
  gradient_accumulation_steps: 1
  save_step: 100

  scheduler:
    name: 'constant_with_warmup'
    num_warmup_steps: 50
    num_training_steps: 600

model:
  pretrained_model_name_or_path: 'runwayml/stable-diffusion-v1-5'
  tokenizer_repeats: 1
  ema_unet: 0
  ema_text_encoder: 0
  enable_xformers: False

data:
  batch_size: 4
  prompt_template: 'prompt_tuning_template/caption.txt'
  caption_file: "/home/yabin/datasets/custom/enma_ai/image_captions.json"
  cache_latents: True
  tag_transforms:
    transforms:
      - _target_: hcpdiff.utils.caption_tools.TagShuffle
      - _target_: hcpdiff.utils.caption_tools.TagDropout
        p: 0.1
      - _target_: hcpdiff.utils.caption_tools.TemplateFill
        word_names:
          pt1: enma_ai

  bucket:
    _target_: hcpdiff.data.bucket.RatioBucket.from_files # aspect ratio bucket
    img_root: '/home/yabin/datasets/custom/enma_ai/'
    target_area: {_target_: "builtins.eval", _args_: ['512*512']}
    num_bucket: 10

data_class: null

```
