### ISSUE TITLE
Bug Report: ConfigAttributeError: Missing key clip_skip

### ISSUE THREAD

**Issue by iamwangyabin** [7eu7d7/HCP-Diffusion#8]
Please add `clip_skip=2` in the cfgs/infer/v1.yaml

Below is my inference config, using enma_ai's lora trained by HCP Diffusion.
```
pretrained_model: /home/yabin/HCP-Diffusion/converted_models/Acertain
prompt: enma_ai, 1girl, tree, solo, plant, bush, outdoors, grass, garden, nature,
  branch, day, sky,
neg_prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit,
  fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,
  signature, watermark, username, blurry
out_dir: output/
emb_dir: embs/
N_repeats: 1
bs: 4
num: 1
seed: null
fp16: true
clip_skip: 2
save:
  save_cfg: true
  image_type: png
  quality: 95
infer_args:
  width: 512
  height: 768
  guidance_scale: 7.5
new_components: {}
merge:
  exp_dir: 2023-04-17-21-59-53
  alpha: 0.8
  group1:
    type: unet
    base_model_alpha: 1.0
    lora:
    - path: exps/${....exp_dir}/ckpts/unet-2000.safetensors
      alpha: ${....alpha}
      layers: all
      mask: null
    part: null
  group2:
    type: TE
    base_model_alpha: 1.0
    lora:
    - path: exps/${....exp_dir}/ckpts/text_encoder-2000.safetensors
      alpha: ${....alpha}
      layers: all
      mask: null
    part: null
```
Below is the generated image with ACertain, which is also the base model I trained on.

![0-enma_ai, 1girl, tree, solo, plant, bush, outdoors, grass, garden, nature, branch, day, sky,](https://user-images.githubusercontent.com/38123329/232534370-05991a29-88f3-4cf0-8626-2fcb88b8a30a.png)

Currently, I am unable to evaluate the quality of this LoRa model compared to my previous [LoRa model](https://civitai.com/models/22308/hell-girl-enma-ai-lora) trained using sd-script, mainly because there are numerous training script settings in this repository that I do not understand. However, I am confident that this is an excellent project. The code is clean and easy to use, with support for training on Linux systems and multiple GPUs. There are many algorithms available (although I am not sure of the exact number of methods that have been implemented).

Expected to see convertion scripts to transfer this lora format to general lora format, which can be used in Webui with more controlable parameters.

By the way, I'm curious about the Rank parameter in the configuration file. Initially, I thought it meant dim in sd-script, but when I set it to 128, the final output model's size was more than 200MB (while this dim setting is only 144MB in sd-script). I also noticed that the scale parameter is available in the code, but currently, I am unable to set it using the configuration file. I believe that the scale is equivalent to 'alpha'.
